Release 5.0.0 - GCP related changes
project-sunbird/sunbird-learning-platform pull request #1788
Opened 2022-11-09 12:39 UTC by santhosh-tg

2022-11-10 09:14 UTC, keshavprasadms approved these changes
Looks good 🦸🏻

2022-11-10 09:16 UTC, keshavprasadms requested changes
@santhosh-tg Please raise against release 5.1.0
@AmiableAnil Please create 5.1.0 branch

2022-11-10 09:17 UTC, keshavprasadms submitted a review, later dismissed

2022-11-11 07:29 UTC, vinukumar-vs approved these changes

2022-11-11 07:30 UTC, merged