Handling google drive url while csp migration
project-sunbird/sunbird-learning-platform pull request #1902
Opened 2023-01-17 06:47 UTC by amitpriyadarshi

2023-01-18 12:44 UTC, maheshkumargangula requested changes

2023-01-18 12:44 UTC, maheshkumargangula commented on kubernetes/helm_charts/datapipeline_jobs/values.j2
> -      enable.distributed.checkpointing = true
Why did you disable the distributed checkpointing?

2023-01-18 12:44 UTC, maheshkumargangula commented on kubernetes/helm_charts/datapipeline_jobs/values.j2
> +    gdrive.application_name=drive-download
Application name also make it configurable. Don't hard-code.

2023-01-19 06:11 UTC, AmiableAnil approved these changes

2023-01-19 06:15 UTC, closed without merging